server:
  port: 9001
spring:
  application:
    name: ceo-service
  datasource:
    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: ceo
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
eureka:
  client:
    enabled: false
